### ISSUE TITLE
コードスタイルの統一化に向けた提案

### ISSUE THREAD

**Issue by barroit** [Caishangqi/CharmingCraft#4]
コードスタイルは、開発者によって異なることが一般的ですが、プロジェクトの効率と可読性を向上させるために、統一されたコードスタイルを推奨します。したがって、既存のコードスタイルに対して、適切な調整を行うことをお勧めします。

**Comment by Caishangqi** [comment]
無視してください、私はあなたが好きです

**Comment by Caishangqi** [comment]
![Uploading Sprite-0006.png…]()
